### ISSUE TITLE
[TencentCloudSDKException] code:InvalidParameterValue message:The value `50` specified in the parameter `SystemDisk.DiskSize` is not valid

### ISSUE THREAD

**Issue by Shengpei-Luke-Chen** [TencentCloud/tencentcloud-sdk-python#12]
我在query instance的价格，是个很简单的函数。用的基本都是默认值。
```python
def query_instance_price(self):
        def instance_obj_2_param(obj):
            param = {
                "Placement": {
                    "Zone": "ap-guangzhou-3"
                },
                "ImageId": "img-lsttqmsl",
                "InstanceChargeType": "POSTPAID_BY_HOUR",
                "InstanceType": "S3.LARGE16",
                "SystemDisk": {
                    "DiskType": "LOCAL_BASIC", 
                },
                "InternetAccessible": {
                    "InternetChargeType": "BANDWIDTH_POSTPAID_BY_HOUR",
                    "InternetMaxBandwidthOut": 10,
                    "PublicIpAssigned": True
                },
                "InstanceCount": 1,
                "LoginSettings": {
                    "Password": obj.root_pwd
                }
            }
            return param

        module = 'cvm'
        action = 'InquiryPriceRunInstances'
        client = cvm_client.CvmClient(self.cred, self.config['region'])
        client._endpoint = self.endpoint.format(module)
        req = models.InquiryPriceRunInstancesRequest()

        params = instance_obj_2_param(instance_obj)
        req.from_json_string(json.dumps(params))

        resp = client.InquiryPriceRunInstances(req)
        return resp
```
得到的错误信息如下。
- 文档说50是默认值
- instance type是作为测试，在广州3区随便选的，应该不是供应的问题？issue #7  说好的广州区没有问题呢 :cold_sweat: 如果是不提供此类存储类型，建议整个exception
```
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    resp = client.compute.query_instance_price(ins)
  File "/Users/macbook/github/AXBio_Schedulers/Standardized_cloud_api/Tencent/compute.py", line 168, in query_instance_price
    resp = client.InquiryPriceRunInstances(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tencentcloud/cvm/v20170312/cvm_client.py", line 1108, in InquiryPriceRunInstances
    raise e
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:InvalidParameterValue message:The value `50` specified in the parameter `SystemDisk.DiskSize` is not valid. requestId:fde3469c-92eb-49c3-9044-d6cbf45a190c
```

Thanks ahead.

**Comment by Shengpei-Luke-Chen** [comment]
我自己找到原因了，就是“此instance type不支持此类DiskType”
而各个instance type所支持的disk type，可以在 `DescribeZoneInstanceConfigInfos` 等里面找到。用户可以自行先检查是否支持，然后再query或者run

我的建议：
- 整个专门的Exception，这报错信息和解决方案之间真的有点距离。有exception用户也好处理一些。
- 在DescribeZoneInstanceConfigInfos里面会列出大量LocalDiskTypeList为空但非sold out的instance type（也就是无法被run和inquiry的instance type）。我建议这部分信息，就不要再（默认）输出了，或者有个flag（如runable，available等）可以快速filter

祝各位诸事顺利 :laughing:

**Comment by zqfan** [comment]
鉴于这个是cvm api的返回，sdk这边目前并不会去做特殊处理，只能靠底层去优化体验问题了。
专门的exception目前来看不会去做，因为错误码实在是太多了，如有对此特殊错误的处理需要，可以捕获通用异常，通过异常的code字段进行错误码判断哈。
