### ISSUE TITLE
'tencentcloud.common.credential' has no attribute 'token'

### ISSUE THREAD

**Issue by CaiCandong** [TencentCloud/tencentcloud-sdk-python#184]
```
from tencentcloud.cdn.v20180606 import cdn_client, models
from tencentcloud.common import credential


cred = credential.Credential(
        "************",
        "************")

client = cdn_client.CdnClient(credential,"ap-guangzhou")

request = models.DescribeCdnDomainLogsRequest()
request.Domain = "****.com"

resp = client.DescribeCdnDomainLogs(request)

```

```
Traceback (most recent call last):
  File "/Users/caicandong/zygit/architecture/cdn-log-exporter/test.py", line 15, in <module>
    client.DescribeCdnDomainLogs(request)
  File "/Users/caicandong/anaconda3/envs/cdn-log-exporter/lib/python3.12/site-packages/tencentcloud/cdn/v20180606/cdn_client.py", line 410, in DescribeCdnDomainLogs
    raise TencentCloudSDKException(type(e).__name__, str(e))
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:AttributeError message:module 'tencentcloud.common.credential' has no attribute 'token' requestId:None
```
已经填入了secret_id和secret_key，报错缺失token，是否是bug?  或者告知一下怎么获取这个token?

**Comment by zqfan** [comment]
麻烦贴一下sdk的版本号，以及pip freeze | grep tencentcloud-sdk （看一下环境上装的到底是什么包）
